# Demo of BiVectors to Identify Rotation Axis and Angle

In [3]:
# Numerical Libraries
import numpy as np
import pandas as pd
# Plotting Libraries
import plotly
import plotly.offline as py
import plotly.graph_objs as go
import plotly.express as px

Custom Written Packages which allow manipulations on the eponymous structures.

In [4]:
# Libraries with Vector and Quaternion Capabilities
import Vector as vctr
import Quaternion as qtrn
# Bi-Vector Library being Demonstrated
import BiVector as bv

## Enter Input Values
Note: Angle between u1,v1 and u2,v2 must remain invariant.

In [5]:
u1 = vctr.Vector(1,1,1)
u2 = vctr.Vector(1,-1,1)
v1 = vctr.Vector(1,0,0)
v2 = vctr.Vector(0,-1,0)

## Bi-Vector Notation

In [6]:
Bvctr1 = bv.BiVector(u1,v1)
Bvctr2 = bv.BiVector(u2,v2)

## Axis_Angle(Bi-Vector_Initial,Bi-Vector_Final)
To find out the Axis and the Angle 

In [7]:
Euler = bv.Axis_Angle(Bvctr1,Bvctr2)
Axis = Euler[0].unit()
Angle = Euler[1]

In [16]:
print(Axis)
print(np.rad2deg(Angle))

x = 0  ;    y = 0 ;   z = -1
90.0


## Visualization 
The green pair is the Initial Bi-Vector, the Blue being the final.
The unconed line segment represents the axis about which the rotation takes place.

In [17]:
O = vctr.Vector(0,0,0)
XYZ = np.array([u1.array(),O.array(),u2.array(),O.array(),v1.array(),O.array(),v2.array(),O.array(),Axis.array(),O.array()])
data2 = {'Dimension': ['X','Y','Z'],
         'u1' : XYZ[0,:],
         'u2' : XYZ[2,:],
         'v1' : XYZ[4,:],
         'v2' : XYZ[6,:],
         'n'  : XYZ[8,:]    
}
df2 = pd.DataFrame(data2, columns = ['Name','u1','u2','v1','v2', 'n'])
data2 = {'Dimension': ['X','Y','Z'],
         'u1' : XYZ[0,:],
         'u2' : XYZ[2,:],
         'v1' : XYZ[4,:],
         'v2' : XYZ[6,:],
         'n'  : XYZ[8,:]    
}
df2 = pd.DataFrame(data2, columns = ['Name','u1','u2','v1','v2', 'n'])
fig = go.Figure()

fig = px.line_3d(x=XYZ[:,0], y=XYZ[:,1], z=XYZ[:,2])

data1=go.Cone(x=XYZ[[0,4],0], y=XYZ[[0,4],1], z=XYZ[[0,4],2], u=XYZ[[0,4],0], v=XYZ[[0,4],1], w=XYZ[[0,4],2],colorscale = [[0, 'limegreen'],[1, 'limegreen']],sizemode="scaled",name = "Bi-Vector 1",showscale=False)
fig.add_trace(data1)
data2=go.Cone(x=XYZ[[2,6],0], y=XYZ[[2,6],1], z=XYZ[[2,6],2], u=XYZ[[2,6],0], v=XYZ[[2,6],1], w=XYZ[[2,6],2],colorscale = [[0, 'aqua'],[1, 'aqua']],sizemode="scaled",name = "Bi-Vector 2", showscale=False)
fig.add_trace(data2)
data3=go.Cone(x=Axis.array()[0].reshape(1,1), y=Axis.array()[1].reshape(1,1), z=Axis.array()[2].reshape(1,1), u=Axis.array()[0].reshape(1,1), v=Axis.array()[1].reshape(1,1), w=Axis.array()[2].reshape(1,1),name = "Axis", showscale=False)
fig.add_trace(data3)

fig.show()

# Rotation Matrix Output 
From Euler Axis-Angle to Rotation Matrix

In [19]:
Theta = 90
Theta_r = np.deg2rad(Theta)
Axis = vctr.Vector(0,0,-1)

In [13]:
Rot_Mat= np.cos(Theta_r)*np.eye(3) + (1 - np.cos(Theta_r))*(Axis.array().reshape(-1,1)@Axis.array().reshape(1,-1)) + np.sin(Theta_r)*(Axis.unit().Cr_Pr())

In [14]:
print(Rot_Mat)

[[ 6.123234e-17  1.000000e+00  0.000000e+00]
 [-1.000000e+00  6.123234e-17  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  1.000000e+00]]
